### ISSUE TITLE
Intent to fork for minimal tiling management

### ISSUE THREAD

**Issue by jadbox** [PapyElGringo/material-shell#101]
This issue is just my notice that I'm starting a fork. I absolutely love this project, but I need more flexibility to shape this extension into something that is much more akin to gnome-with-tiling than replace-gnome-ui-with-material direction.

This is in reference to my work in the prototype PR #100. It's a good starting point for why I decided to run in this direction.

For the time being, I've decided to go ahead with a fork ([BreezyTile](https://github.com/jadbox/BreezyTile)) until we have a better plan. This will allow me to move quicker patching this as just a lightweight window manager without any additional panels or changes to gnome behaviors (outside of tiling behavior).

I'm open to compromise and dialing back the fork if there's an appetite to have an option to have Material-Shell toggle into a kind of "lightweight" mode, although there might be some complexity in maintaining these two modes together. Thoughts are welcome. 

https://github.com/jadbox/BreezyTile

**Comment by PapyElGringo** [comment]
Like I said in the PR:
Since the multiple tiling layouts are just a bonus in the point of view of Material-shell keeping only this doesn't make sense for Material-shell. And if I wanted to only provide tiling capabilities for Gnome-shell I wouldn't keep the current algorithm as it's made to work specifically with ou SuperWorkspaces which don't make any sense in the legacy gnome. 
And do you there is already a lot of project that worked on providing tiling capabilities to gnome-shell?
https://github.com/ChWick/gnomesome
https://github.com/timbertson/shellshape
https://github.com/paperwm/PaperWM

I really don't imagine an option in material-shell for this.

**Comment by jadbox** [comment]
@PapyElGringo first of all, I want to really say THANK YOU for all your super hard work. :)

I've tried all the tiling managers you mentioned (and more), and I've yet to find something that 'clicks' for me as does the tiling in material-shell. I think this boils down to the ability to move windows in the mosaic layout to different positions as needed. I don't need to learn any fancy hotkeys- just simple mouse controlled window management.

I totally understand and respect that what I'm trying to do falls outside of material-shell. As much as I think the 'material' part of this project is interesting, at this moment I'd prefer to keep my gnome panels around (and their own customizations/extensions).
