### ISSUE TITLE
Split extension into smaller ones?

### ISSUE THREAD

**Issue by benneti** [PapyElGringo/material-shell#12]
Hi, thank you for the nice extension, do you think it would be possible to seperate this extension in a few smaller ones?
E.g. I would like to only use the tiling part, but with the workspace management and interface of gnome.

**Comment by Danmou** [comment]
I agree, as it is this extension feels a bit too invasive. I don't like having my top bar transformed into a side bar, for example, and I don\t really need the tabs for applications on the top. Also, I might not want to use the workspace switcher and application launcher with different categories that material-shell comes with.

You don't strictly have to make several extensions, as long as all these things can be disabled in the settings (or maybe even come disabled by default, to ease the transition from whatever configuration the user was using before). But I think at least separating the tiling WM and the rest of the UI would make sense, because either of those things could be useful on their own, and thus reach a larger audience (actually I think the tabs for applications would be more useful in a non-tiling setting).

Anyway keep up the good work, I'm excited to see where this goes!

**Comment by PapyElGringo** [comment]
You will probably more intrested on other projects like [gnomesome](https://github.com/ChWick/gnomesome) or [paperwm](https://github.com/paperwm/PaperWM)

**Comment by PapyElGringo** [comment]
and if you just don't like the panels https://github.com/PapyElGringo/material-shell/issues/49 this could help you to don't see them.
