### ISSUE TITLE
Consider Deprecating Next/Prev Workspace and Kill Settings for existing Gnome Keyboard Shortcuts

### ISSUE THREAD

**Issue by jeffwindsor** [PapyElGringo/material-shell#64]
`org.gnome.desktop.wm.keybindings close` for `org.gnome.shell.extensions.materialshell.bindings kill-focused-window`

`org.gnome.desktop.wm.keybindings switch-to-workspace-up` for `org.gnome.shell.extensions.materialshell.bindings previous-workspace`

`org.gnome.desktop.wm.keybindings switch-to-workspace-down` for `org.gnome.shell.extensions.materialshell.bindings next-workspace`

**Comment by jeffwindsor** [comment]
This is a suggestion based on a minimalist point of view, in which extensions add what is needed an no more.  If that is not where you guys are going then please ignore the suggestion.

**Comment by PapyElGringo** [comment]
Hello @jeffwindsor and thanks for your contribution ! Minimal approach is often the best way to go because the less features you have the easier it's to maintained it. That's said I wan't Material-shell to be usable just after being installed without any extra configuration. Duplicating some of the default hotkeys allow me to give default configuration for them and propose a predefined workflow experience.

**Comment by jeffwindsor** [comment]
No problem, that is reasonable.
